/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Air3550
{
    public partial class AccountantTicketForm : Form
    {
        public AccountantTicketForm()
        {
            InitializeComponent();
        }

        //do nothing here, autogenerated
        private void AccountantTicketForm_Load(object sender, EventArgs e)
        {

        }

        //Set all applicable values for UI
        public void setUIValues(string flightNumber, string flightDate, string totalIncome, string maxCapacity, string ticketsSold, string percentFull)
        {
            flightNumberLabel.Text = flightNumber;
            flightDateLabel.Text = flightDate;
            totalIncomeFlightLabel.Text = totalIncome;
            maxCapacityFlightLabel.Text = maxCapacity;
            ticketsSoldFlightLabel.Text = ticketsSold;
            percentFullFlightLabel.Text = percentFull;
        }
    }
}
