/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //this is autogenerated code from winforms
    partial class AccountInfoMainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label8 = new System.Windows.Forms.Label();
            this.lastNameText = new System.Windows.Forms.TextBox();
            this.lastNameOutline = new System.Windows.Forms.Panel();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.billingText = new System.Windows.Forms.TextBox();
            this.ageText = new System.Windows.Forms.TextBox();
            this.phoneText = new System.Windows.Forms.TextBox();
            this.addressText = new System.Windows.Forms.TextBox();
            this.nameText = new System.Windows.Forms.TextBox();
            this.nameOutline = new System.Windows.Forms.Panel();
            this.ageOutline = new System.Windows.Forms.Panel();
            this.billingOutline = new System.Windows.Forms.Panel();
            this.addressOutline = new System.Windows.Forms.Panel();
            this.numberOutline = new System.Windows.Forms.Panel();
            this.discardChangesButton = new System.Windows.Forms.Button();
            this.saveChangeButton = new System.Windows.Forms.Button();
            this.pointsLabel = new System.Windows.Forms.Label();
            this.changePasswordButton = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // label8
            // 
            this.label8.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label8.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label8.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label8.Location = new System.Drawing.Point(154, 202);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(158, 18);
            this.label8.TabIndex = 60;
            this.label8.Text = "Last Name";
            // 
            // lastNameText
            // 
            this.lastNameText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lastNameText.BackColor = System.Drawing.SystemColors.Window;
            this.lastNameText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lastNameText.ForeColor = System.Drawing.SystemColors.WindowText;
            this.lastNameText.Location = new System.Drawing.Point(154, 225);
            this.lastNameText.Name = "lastNameText";
            this.lastNameText.ReadOnly = true;
            this.lastNameText.Size = new System.Drawing.Size(262, 33);
            this.lastNameText.TabIndex = 56;
            // 
            // lastNameOutline
            // 
            this.lastNameOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lastNameOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.lastNameOutline.Location = new System.Drawing.Point(151, 223);
            this.lastNameOutline.Name = "lastNameOutline";
            this.lastNameOutline.Padding = new System.Windows.Forms.Padding(2);
            this.lastNameOutline.Size = new System.Drawing.Size(269, 38);
            this.lastNameOutline.TabIndex = 57;
            // 
            // label7
            // 
            this.label7.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label7.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label7.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label7.Location = new System.Drawing.Point(523, 134);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(158, 18);
            this.label7.TabIndex = 49;
            this.label7.Text = "Age";
            // 
            // label6
            // 
            this.label6.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label6.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label6.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label6.Location = new System.Drawing.Point(523, 207);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(158, 18);
            this.label6.TabIndex = 48;
            this.label6.Text = "Billing Information";
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label4.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label4.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label4.Location = new System.Drawing.Point(154, 278);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(158, 18);
            this.label4.TabIndex = 46;
            this.label4.Text = "Phone Number";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label3.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label3.Location = new System.Drawing.Point(154, 340);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(158, 18);
            this.label3.TabIndex = 45;
            this.label3.Text = "Address";
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label1.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label1.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label1.Location = new System.Drawing.Point(154, 134);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(158, 18);
            this.label1.TabIndex = 44;
            this.label1.Text = "First Name";
            // 
            // billingText
            // 
            this.billingText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.billingText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.billingText.Location = new System.Drawing.Point(523, 228);
            this.billingText.Name = "billingText";
            this.billingText.ReadOnly = true;
            this.billingText.Size = new System.Drawing.Size(262, 33);
            this.billingText.TabIndex = 43;
            // 
            // ageText
            // 
            this.ageText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.ageText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ageText.Location = new System.Drawing.Point(523, 155);
            this.ageText.Name = "ageText";
            this.ageText.ReadOnly = true;
            this.ageText.Size = new System.Drawing.Size(262, 33);
            this.ageText.TabIndex = 41;
            // 
            // phoneText
            // 
            this.phoneText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.phoneText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.phoneText.Location = new System.Drawing.Point(154, 299);
            this.phoneText.Name = "phoneText";
            this.phoneText.ReadOnly = true;
            this.phoneText.Size = new System.Drawing.Size(262, 33);
            this.phoneText.TabIndex = 40;
            // 
            // addressText
            // 
            this.addressText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.addressText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.addressText.Location = new System.Drawing.Point(154, 361);
            this.addressText.Name = "addressText";
            this.addressText.ReadOnly = true;
            this.addressText.Size = new System.Drawing.Size(262, 33);
            this.addressText.TabIndex = 39;
            // 
            // nameText
            // 
            this.nameText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.nameText.BackColor = System.Drawing.SystemColors.Window;
            this.nameText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.nameText.ForeColor = System.Drawing.SystemColors.WindowText;
            this.nameText.Location = new System.Drawing.Point(154, 155);
            this.nameText.Name = "nameText";
            this.nameText.ReadOnly = true;
            this.nameText.Size = new System.Drawing.Size(262, 33);
            this.nameText.TabIndex = 38;
            // 
            // nameOutline
            // 
            this.nameOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.nameOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.nameOutline.Location = new System.Drawing.Point(151, 153);
            this.nameOutline.Name = "nameOutline";
            this.nameOutline.Padding = new System.Windows.Forms.Padding(2);
            this.nameOutline.Size = new System.Drawing.Size(269, 38);
            this.nameOutline.TabIndex = 50;
            // 
            // ageOutline
            // 
            this.ageOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.ageOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.ageOutline.Location = new System.Drawing.Point(519, 153);
            this.ageOutline.Name = "ageOutline";
            this.ageOutline.Padding = new System.Windows.Forms.Padding(2);
            this.ageOutline.Size = new System.Drawing.Size(269, 38);
            this.ageOutline.TabIndex = 51;
            // 
            // billingOutline
            // 
            this.billingOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.billingOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.billingOutline.Location = new System.Drawing.Point(520, 225);
            this.billingOutline.Name = "billingOutline";
            this.billingOutline.Padding = new System.Windows.Forms.Padding(2);
            this.billingOutline.Size = new System.Drawing.Size(269, 38);
            this.billingOutline.TabIndex = 52;
            // 
            // addressOutline
            // 
            this.addressOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.addressOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.addressOutline.Location = new System.Drawing.Point(151, 359);
            this.addressOutline.Name = "addressOutline";
            this.addressOutline.Padding = new System.Windows.Forms.Padding(2);
            this.addressOutline.Size = new System.Drawing.Size(269, 38);
            this.addressOutline.TabIndex = 54;
            // 
            // numberOutline
            // 
            this.numberOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numberOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.numberOutline.Location = new System.Drawing.Point(151, 296);
            this.numberOutline.Name = "numberOutline";
            this.numberOutline.Padding = new System.Windows.Forms.Padding(2);
            this.numberOutline.Size = new System.Drawing.Size(269, 38);
            this.numberOutline.TabIndex = 53;
            // 
            // discardChangesButton
            // 
            this.discardChangesButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.discardChangesButton.BackColor = System.Drawing.Color.Red;
            this.discardChangesButton.FlatAppearance.BorderSize = 0;
            this.discardChangesButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.discardChangesButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.discardChangesButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.discardChangesButton.Location = new System.Drawing.Point(513, 441);
            this.discardChangesButton.Name = "discardChangesButton";
            this.discardChangesButton.Size = new System.Drawing.Size(316, 40);
            this.discardChangesButton.TabIndex = 63;
            this.discardChangesButton.Text = "Discard Changes";
            this.discardChangesButton.UseVisualStyleBackColor = false;
            this.discardChangesButton.Visible = false;
            this.discardChangesButton.Click += new System.EventHandler(this.discardChangesButton_Click);
            // 
            // saveChangeButton
            // 
            this.saveChangeButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.saveChangeButton.BackColor = System.Drawing.Color.Red;
            this.saveChangeButton.FlatAppearance.BorderSize = 0;
            this.saveChangeButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.saveChangeButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.saveChangeButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.saveChangeButton.Location = new System.Drawing.Point(111, 441);
            this.saveChangeButton.Name = "saveChangeButton";
            this.saveChangeButton.Size = new System.Drawing.Size(316, 40);
            this.saveChangeButton.TabIndex = 64;
            this.saveChangeButton.Text = "Save Changes";
            this.saveChangeButton.UseVisualStyleBackColor = false;
            this.saveChangeButton.Visible = false;
            this.saveChangeButton.Click += new System.EventHandler(this.button1_Click);
            // 
            // pointsLabel
            // 
            this.pointsLabel.AutoSize = true;
            this.pointsLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.pointsLabel.ForeColor = System.Drawing.Color.White;
            this.pointsLabel.Location = new System.Drawing.Point(12, 9);
            this.pointsLabel.Name = "pointsLabel";
            this.pointsLabel.Size = new System.Drawing.Size(97, 29);
            this.pointsLabel.TabIndex = 77;
            this.pointsLabel.Text = "Points:";
            // 
            // changePasswordButton
            // 
            this.changePasswordButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.changePasswordButton.BackColor = System.Drawing.Color.Red;
            this.changePasswordButton.FlatAppearance.BorderSize = 0;
            this.changePasswordButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.changePasswordButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.changePasswordButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.changePasswordButton.Location = new System.Drawing.Point(566, 318);
            this.changePasswordButton.Name = "changePasswordButton";
            this.changePasswordButton.Size = new System.Drawing.Size(173, 40);
            this.changePasswordButton.TabIndex = 78;
            this.changePasswordButton.Text = "Change Password";
            this.changePasswordButton.UseVisualStyleBackColor = false;
            this.changePasswordButton.Click += new System.EventHandler(this.changePasswordButton_Click);
            // 
            // AccountInfoMainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.ClientSize = new System.Drawing.Size(940, 532);
            this.Controls.Add(this.changePasswordButton);
            this.Controls.Add(this.pointsLabel);
            this.Controls.Add(this.saveChangeButton);
            this.Controls.Add(this.discardChangesButton);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.lastNameText);
            this.Controls.Add(this.lastNameOutline);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.billingText);
            this.Controls.Add(this.ageText);
            this.Controls.Add(this.phoneText);
            this.Controls.Add(this.addressText);
            this.Controls.Add(this.nameText);
            this.Controls.Add(this.nameOutline);
            this.Controls.Add(this.ageOutline);
            this.Controls.Add(this.billingOutline);
            this.Controls.Add(this.addressOutline);
            this.Controls.Add(this.numberOutline);
            this.Name = "AccountInfoMainForm";
            this.Text = "AccountInfoMainForm";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox lastNameText;
        private System.Windows.Forms.Panel lastNameOutline;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox billingText;
        private System.Windows.Forms.TextBox ageText;
        private System.Windows.Forms.TextBox phoneText;
        private System.Windows.Forms.TextBox addressText;
        private System.Windows.Forms.TextBox nameText;
        private System.Windows.Forms.Panel nameOutline;
        private System.Windows.Forms.Panel ageOutline;
        private System.Windows.Forms.Panel billingOutline;
        private System.Windows.Forms.Panel addressOutline;
        private System.Windows.Forms.Panel numberOutline;
        private System.Windows.Forms.Button discardChangesButton;
        private System.Windows.Forms.Button saveChangeButton;
        private System.Windows.Forms.Label pointsLabel;
        private System.Windows.Forms.Button changePasswordButton;
    }
}