/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //this is autogenerated code from winforms
    partial class AccountInfoTopForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.changeAccountInfoButton = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // changeAccountInfoButton
            // 
            this.changeAccountInfoButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.changeAccountInfoButton.BackColor = System.Drawing.Color.Red;
            this.changeAccountInfoButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.changeAccountInfoButton.FlatAppearance.BorderSize = 0;
            this.changeAccountInfoButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.changeAccountInfoButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.changeAccountInfoButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.changeAccountInfoButton.Location = new System.Drawing.Point(312, 31);
            this.changeAccountInfoButton.Name = "changeAccountInfoButton";
            this.changeAccountInfoButton.Size = new System.Drawing.Size(316, 40);
            this.changeAccountInfoButton.TabIndex = 12;
            this.changeAccountInfoButton.TabStop = false;
            this.changeAccountInfoButton.Text = "Change Account Information";
            this.changeAccountInfoButton.UseVisualStyleBackColor = false;
            this.changeAccountInfoButton.Click += new System.EventHandler(this.changeAccountInfoButton_Click);
            // 
            // AccountInfoTopForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.ClientSize = new System.Drawing.Size(940, 102);
            this.Controls.Add(this.changeAccountInfoButton);
            this.Name = "AccountInfoTopForm";
            this.Text = "AccountInfoTopForm";
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.Button changeAccountInfoButton;
    }
}