/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //This is autogenerated code from winforms
    partial class BoardingPassPopUpForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(BoardingPassPopUpForm));
            this.firstDepartLabel = new System.Windows.Forms.Label();
            this.firstArrivalLabel = new System.Windows.Forms.Label();
            this.firstDepartTimeLabel = new System.Windows.Forms.Label();
            this.firstArrivalTimeLabel = new System.Windows.Forms.Label();
            this.secondDepartLabel = new System.Windows.Forms.Label();
            this.secondArrivalLabel = new System.Windows.Forms.Label();
            this.secondDepartTimeLabel = new System.Windows.Forms.Label();
            this.secondArrivalTimeLabel = new System.Windows.Forms.Label();
            this.secondFlightNumberDateLabel = new System.Windows.Forms.Label();
            this.firstFlightDateLabel = new System.Windows.Forms.Label();
            this.firstNameLabel = new System.Windows.Forms.Label();
            this.lastNameLabel = new System.Windows.Forms.Label();
            this.accountNumberLabel = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.secondFlightNumberLabel = new System.Windows.Forms.Label();
            this.firstFlightNumberLabel = new System.Windows.Forms.Label();
            this.exitPassButton = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // firstDepartLabel
            // 
            this.firstDepartLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstDepartLabel.AutoSize = true;
            this.firstDepartLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstDepartLabel.ForeColor = System.Drawing.Color.White;
            this.firstDepartLabel.Location = new System.Drawing.Point(24, 68);
            this.firstDepartLabel.Name = "firstDepartLabel";
            this.firstDepartLabel.Size = new System.Drawing.Size(61, 29);
            this.firstDepartLabel.TabIndex = 83;
            this.firstDepartLabel.Text = "AAA";
            // 
            // firstArrivalLabel
            // 
            this.firstArrivalLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstArrivalLabel.AutoSize = true;
            this.firstArrivalLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstArrivalLabel.ForeColor = System.Drawing.Color.White;
            this.firstArrivalLabel.Location = new System.Drawing.Point(123, 68);
            this.firstArrivalLabel.Name = "firstArrivalLabel";
            this.firstArrivalLabel.Size = new System.Drawing.Size(58, 29);
            this.firstArrivalLabel.TabIndex = 84;
            this.firstArrivalLabel.Text = "ZZZ";
            // 
            // firstDepartTimeLabel
            // 
            this.firstDepartTimeLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstDepartTimeLabel.AutoSize = true;
            this.firstDepartTimeLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstDepartTimeLabel.ForeColor = System.Drawing.Color.White;
            this.firstDepartTimeLabel.Location = new System.Drawing.Point(24, 115);
            this.firstDepartTimeLabel.Name = "firstDepartTimeLabel";
            this.firstDepartTimeLabel.Size = new System.Drawing.Size(67, 29);
            this.firstDepartTimeLabel.TabIndex = 85;
            this.firstDepartTimeLabel.Text = "2:30";
            // 
            // firstArrivalTimeLabel
            // 
            this.firstArrivalTimeLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstArrivalTimeLabel.AutoSize = true;
            this.firstArrivalTimeLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstArrivalTimeLabel.ForeColor = System.Drawing.Color.White;
            this.firstArrivalTimeLabel.Location = new System.Drawing.Point(123, 115);
            this.firstArrivalTimeLabel.Name = "firstArrivalTimeLabel";
            this.firstArrivalTimeLabel.Size = new System.Drawing.Size(67, 29);
            this.firstArrivalTimeLabel.TabIndex = 86;
            this.firstArrivalTimeLabel.Text = "3:30";
            // 
            // secondDepartLabel
            // 
            this.secondDepartLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.secondDepartLabel.AutoSize = true;
            this.secondDepartLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.secondDepartLabel.ForeColor = System.Drawing.Color.White;
            this.secondDepartLabel.Location = new System.Drawing.Point(24, 230);
            this.secondDepartLabel.Name = "secondDepartLabel";
            this.secondDepartLabel.Size = new System.Drawing.Size(61, 29);
            this.secondDepartLabel.TabIndex = 87;
            this.secondDepartLabel.Text = "AAA";
            this.secondDepartLabel.Visible = false;
            // 
            // secondArrivalLabel
            // 
            this.secondArrivalLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.secondArrivalLabel.AutoSize = true;
            this.secondArrivalLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.secondArrivalLabel.ForeColor = System.Drawing.Color.White;
            this.secondArrivalLabel.Location = new System.Drawing.Point(123, 230);
            this.secondArrivalLabel.Name = "secondArrivalLabel";
            this.secondArrivalLabel.Size = new System.Drawing.Size(58, 29);
            this.secondArrivalLabel.TabIndex = 88;
            this.secondArrivalLabel.Text = "ZZZ";
            this.secondArrivalLabel.Visible = false;
            // 
            // secondDepartTimeLabel
            // 
            this.secondDepartTimeLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.secondDepartTimeLabel.AutoSize = true;
            this.secondDepartTimeLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.secondDepartTimeLabel.ForeColor = System.Drawing.Color.White;
            this.secondDepartTimeLabel.Location = new System.Drawing.Point(24, 280);
            this.secondDepartTimeLabel.Name = "secondDepartTimeLabel";
            this.secondDepartTimeLabel.Size = new System.Drawing.Size(67, 29);
            this.secondDepartTimeLabel.TabIndex = 89;
            this.secondDepartTimeLabel.Text = "3:30";
            this.secondDepartTimeLabel.Visible = false;
            // 
            // secondArrivalTimeLabel
            // 
            this.secondArrivalTimeLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.secondArrivalTimeLabel.AutoSize = true;
            this.secondArrivalTimeLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.secondArrivalTimeLabel.ForeColor = System.Drawing.Color.White;
            this.secondArrivalTimeLabel.Location = new System.Drawing.Point(123, 280);
            this.secondArrivalTimeLabel.Name = "secondArrivalTimeLabel";
            this.secondArrivalTimeLabel.Size = new System.Drawing.Size(67, 29);
            this.secondArrivalTimeLabel.TabIndex = 90;
            this.secondArrivalTimeLabel.Text = "4:30";
            this.secondArrivalTimeLabel.Visible = false;
            // 
            // secondFlightNumberDateLabel
            // 
            this.secondFlightNumberDateLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.secondFlightNumberDateLabel.AutoSize = true;
            this.secondFlightNumberDateLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.secondFlightNumberDateLabel.ForeColor = System.Drawing.Color.White;
            this.secondFlightNumberDateLabel.Location = new System.Drawing.Point(37, 201);
            this.secondFlightNumberDateLabel.Name = "secondFlightNumberDateLabel";
            this.secondFlightNumberDateLabel.Size = new System.Drawing.Size(131, 29);
            this.secondFlightNumberDateLabel.TabIndex = 91;
            this.secondFlightNumberDateLabel.Text = "1/6/2021";
            this.secondFlightNumberDateLabel.Visible = false;
            // 
            // firstFlightDateLabel
            // 
            this.firstFlightDateLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstFlightDateLabel.AutoSize = true;
            this.firstFlightDateLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstFlightDateLabel.ForeColor = System.Drawing.Color.White;
            this.firstFlightDateLabel.Location = new System.Drawing.Point(37, 39);
            this.firstFlightDateLabel.Name = "firstFlightDateLabel";
            this.firstFlightDateLabel.Size = new System.Drawing.Size(131, 29);
            this.firstFlightDateLabel.TabIndex = 92;
            this.firstFlightDateLabel.Text = "1/5/2021";
            // 
            // firstNameLabel
            // 
            this.firstNameLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstNameLabel.AutoSize = true;
            this.firstNameLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstNameLabel.ForeColor = System.Drawing.Color.White;
            this.firstNameLabel.Location = new System.Drawing.Point(290, 230);
            this.firstNameLabel.Name = "firstNameLabel";
            this.firstNameLabel.Size = new System.Drawing.Size(132, 29);
            this.firstNameLabel.TabIndex = 93;
            this.firstNameLabel.Text = "Firstname";
            // 
            // lastNameLabel
            // 
            this.lastNameLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lastNameLabel.AutoSize = true;
            this.lastNameLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lastNameLabel.ForeColor = System.Drawing.Color.White;
            this.lastNameLabel.Location = new System.Drawing.Point(290, 280);
            this.lastNameLabel.Name = "lastNameLabel";
            this.lastNameLabel.Size = new System.Drawing.Size(133, 29);
            this.lastNameLabel.TabIndex = 94;
            this.lastNameLabel.Text = "LastName";
            // 
            // accountNumberLabel
            // 
            this.accountNumberLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.accountNumberLabel.AutoSize = true;
            this.accountNumberLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.accountNumberLabel.ForeColor = System.Drawing.Color.White;
            this.accountNumberLabel.Location = new System.Drawing.Point(404, 330);
            this.accountNumberLabel.Name = "accountNumberLabel";
            this.accountNumberLabel.Size = new System.Drawing.Size(103, 29);
            this.accountNumberLabel.TabIndex = 95;
            this.accountNumberLabel.Text = "608432";
            // 
            // label13
            // 
            this.label13.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label13.ForeColor = System.Drawing.Color.White;
            this.label13.Location = new System.Drawing.Point(183, 330);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(215, 29);
            this.label13.TabIndex = 96;
            this.label13.Text = "AccountNumber:";
            // 
            // secondFlightNumberLabel
            // 
            this.secondFlightNumberLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.secondFlightNumberLabel.AutoSize = true;
            this.secondFlightNumberLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.secondFlightNumberLabel.ForeColor = System.Drawing.Color.White;
            this.secondFlightNumberLabel.Location = new System.Drawing.Point(12, 172);
            this.secondFlightNumberLabel.Name = "secondFlightNumberLabel";
            this.secondFlightNumberLabel.Size = new System.Drawing.Size(186, 29);
            this.secondFlightNumberLabel.TabIndex = 97;
            this.secondFlightNumberLabel.Text = "FlightNumber:";
            this.secondFlightNumberLabel.Visible = false;
            // 
            // firstFlightNumberLabel
            // 
            this.firstFlightNumberLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstFlightNumberLabel.AutoSize = true;
            this.firstFlightNumberLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstFlightNumberLabel.ForeColor = System.Drawing.Color.White;
            this.firstFlightNumberLabel.Location = new System.Drawing.Point(12, 9);
            this.firstFlightNumberLabel.Name = "firstFlightNumberLabel";
            this.firstFlightNumberLabel.Size = new System.Drawing.Size(186, 29);
            this.firstFlightNumberLabel.TabIndex = 98;
            this.firstFlightNumberLabel.Text = "FlightNumber:";
            // 
            // exitPassButton
            // 
            this.exitPassButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.exitPassButton.BackColor = System.Drawing.Color.Red;
            this.exitPassButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.exitPassButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.exitPassButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.exitPassButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.exitPassButton.Location = new System.Drawing.Point(696, 406);
            this.exitPassButton.Name = "exitPassButton";
            this.exitPassButton.Size = new System.Drawing.Size(92, 32);
            this.exitPassButton.TabIndex = 99;
            this.exitPassButton.Text = "Exit";
            this.exitPassButton.UseVisualStyleBackColor = false;
            this.exitPassButton.Click += new System.EventHandler(this.exitPassButton_Click);
            // 
            // BoardingPassPopUpForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.exitPassButton);
            this.Controls.Add(this.firstFlightNumberLabel);
            this.Controls.Add(this.secondFlightNumberLabel);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.accountNumberLabel);
            this.Controls.Add(this.lastNameLabel);
            this.Controls.Add(this.firstNameLabel);
            this.Controls.Add(this.firstFlightDateLabel);
            this.Controls.Add(this.secondFlightNumberDateLabel);
            this.Controls.Add(this.secondArrivalTimeLabel);
            this.Controls.Add(this.secondDepartTimeLabel);
            this.Controls.Add(this.secondArrivalLabel);
            this.Controls.Add(this.secondDepartLabel);
            this.Controls.Add(this.firstArrivalTimeLabel);
            this.Controls.Add(this.firstDepartTimeLabel);
            this.Controls.Add(this.firstArrivalLabel);
            this.Controls.Add(this.firstDepartLabel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "BoardingPassPopUpForm";
            this.Text = "BoardingPassPopUpForm";
            this.Load += new System.EventHandler(this.BoardingPassPopUpForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label firstDepartLabel;
        private System.Windows.Forms.Label firstArrivalLabel;
        private System.Windows.Forms.Label firstDepartTimeLabel;
        private System.Windows.Forms.Label firstArrivalTimeLabel;
        private System.Windows.Forms.Label secondDepartLabel;
        private System.Windows.Forms.Label secondArrivalLabel;
        private System.Windows.Forms.Label secondDepartTimeLabel;
        private System.Windows.Forms.Label secondArrivalTimeLabel;
        private System.Windows.Forms.Label secondFlightNumberDateLabel;
        private System.Windows.Forms.Label firstFlightDateLabel;
        private System.Windows.Forms.Label firstNameLabel;
        private System.Windows.Forms.Label lastNameLabel;
        private System.Windows.Forms.Label accountNumberLabel;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label secondFlightNumberLabel;
        private System.Windows.Forms.Label firstFlightNumberLabel;
        private System.Windows.Forms.Button exitPassButton;
    }
}