/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //this is autogenerated code from winforms
    partial class BookFlight
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(BookFlight));
            this.cancelTransactionButton = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.totalPriceLabel = new System.Windows.Forms.Label();
            this.secondPriceLabel = new System.Windows.Forms.Label();
            this.firstPriceLabel = new System.Windows.Forms.Label();
            this.bookFlightsFinalButton = new System.Windows.Forms.Button();
            this.finalPriceLabel = new System.Windows.Forms.Label();
            this.currentPointsLabel = new System.Windows.Forms.Label();
            this.departFirstAirportLabel = new System.Windows.Forms.Label();
            this.departSecondAirportLabel = new System.Windows.Forms.Label();
            this.arriveFirstAirportLabel = new System.Windows.Forms.Label();
            this.arriveAirportLabel = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.legsFirstLabel = new System.Windows.Forms.Label();
            this.legsSecondLabel = new System.Windows.Forms.Label();
            this.pointsValueLabel = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.usePointsCheckBox = new System.Windows.Forms.CheckBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // cancelTransactionButton
            // 
            this.cancelTransactionButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.cancelTransactionButton.BackColor = System.Drawing.Color.Red;
            this.cancelTransactionButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.cancelTransactionButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cancelTransactionButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.cancelTransactionButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.cancelTransactionButton.Location = new System.Drawing.Point(661, 399);
            this.cancelTransactionButton.Name = "cancelTransactionButton";
            this.cancelTransactionButton.Size = new System.Drawing.Size(127, 39);
            this.cancelTransactionButton.TabIndex = 92;
            this.cancelTransactionButton.Text = "Cancel";
            this.cancelTransactionButton.UseVisualStyleBackColor = false;
            this.cancelTransactionButton.Click += new System.EventHandler(this.cancelTransactionButton_Click);
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(12, 9);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(174, 29);
            this.label3.TabIndex = 91;
            this.label3.Text = "Transactions:";
            // 
            // totalPriceLabel
            // 
            this.totalPriceLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.totalPriceLabel.AutoSize = true;
            this.totalPriceLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.totalPriceLabel.ForeColor = System.Drawing.Color.White;
            this.totalPriceLabel.Location = new System.Drawing.Point(507, 382);
            this.totalPriceLabel.Name = "totalPriceLabel";
            this.totalPriceLabel.Size = new System.Drawing.Size(43, 29);
            this.totalPriceLabel.TabIndex = 90;
            this.totalPriceLabel.Text = "20";
            // 
            // secondPriceLabel
            // 
            this.secondPriceLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.secondPriceLabel.AutoSize = true;
            this.secondPriceLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.secondPriceLabel.ForeColor = System.Drawing.Color.White;
            this.secondPriceLabel.Location = new System.Drawing.Point(496, 261);
            this.secondPriceLabel.Name = "secondPriceLabel";
            this.secondPriceLabel.Size = new System.Drawing.Size(58, 29);
            this.secondPriceLabel.TabIndex = 89;
            this.secondPriceLabel.Text = "$20";
            this.secondPriceLabel.Visible = false;
            // 
            // firstPriceLabel
            // 
            this.firstPriceLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.firstPriceLabel.AutoSize = true;
            this.firstPriceLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.firstPriceLabel.ForeColor = System.Drawing.Color.White;
            this.firstPriceLabel.Location = new System.Drawing.Point(496, 108);
            this.firstPriceLabel.Name = "firstPriceLabel";
            this.firstPriceLabel.Size = new System.Drawing.Size(58, 29);
            this.firstPriceLabel.TabIndex = 88;
            this.firstPriceLabel.Text = "$20";
            // 
            // bookFlightsFinalButton
            // 
            this.bookFlightsFinalButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bookFlightsFinalButton.BackColor = System.Drawing.Color.Red;
            this.bookFlightsFinalButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.bookFlightsFinalButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bookFlightsFinalButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.bookFlightsFinalButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bookFlightsFinalButton.Location = new System.Drawing.Point(663, 334);
            this.bookFlightsFinalButton.Name = "bookFlightsFinalButton";
            this.bookFlightsFinalButton.Size = new System.Drawing.Size(127, 39);
            this.bookFlightsFinalButton.TabIndex = 87;
            this.bookFlightsFinalButton.Text = "Book Flight";
            this.bookFlightsFinalButton.UseVisualStyleBackColor = false;
            this.bookFlightsFinalButton.Click += new System.EventHandler(this.bookFlightsFinalButton_Click);
            // 
            // finalPriceLabel
            // 
            this.finalPriceLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.finalPriceLabel.AutoSize = true;
            this.finalPriceLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.finalPriceLabel.ForeColor = System.Drawing.Color.White;
            this.finalPriceLabel.Location = new System.Drawing.Point(12, 382);
            this.finalPriceLabel.Name = "finalPriceLabel";
            this.finalPriceLabel.Size = new System.Drawing.Size(150, 29);
            this.finalPriceLabel.TabIndex = 93;
            this.finalPriceLabel.Text = "Total Price:";
            // 
            // currentPointsLabel
            // 
            this.currentPointsLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.currentPointsLabel.AutoSize = true;
            this.currentPointsLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.currentPointsLabel.ForeColor = System.Drawing.Color.White;
            this.currentPointsLabel.Location = new System.Drawing.Point(507, 9);
            this.currentPointsLabel.Name = "currentPointsLabel";
            this.currentPointsLabel.Size = new System.Drawing.Size(104, 29);
            this.currentPointsLabel.TabIndex = 94;
            this.currentPointsLabel.Text = "Points: ";
            // 
            // departFirstAirportLabel
            // 
            this.departFirstAirportLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.departFirstAirportLabel.AutoSize = true;
            this.departFirstAirportLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.departFirstAirportLabel.ForeColor = System.Drawing.Color.White;
            this.departFirstAirportLabel.Location = new System.Drawing.Point(12, 108);
            this.departFirstAirportLabel.Name = "departFirstAirportLabel";
            this.departFirstAirportLabel.Size = new System.Drawing.Size(61, 29);
            this.departFirstAirportLabel.TabIndex = 95;
            this.departFirstAirportLabel.Text = "AAA";
            // 
            // departSecondAirportLabel
            // 
            this.departSecondAirportLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.departSecondAirportLabel.AutoSize = true;
            this.departSecondAirportLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.departSecondAirportLabel.ForeColor = System.Drawing.Color.White;
            this.departSecondAirportLabel.Location = new System.Drawing.Point(12, 261);
            this.departSecondAirportLabel.Name = "departSecondAirportLabel";
            this.departSecondAirportLabel.Size = new System.Drawing.Size(61, 29);
            this.departSecondAirportLabel.TabIndex = 96;
            this.departSecondAirportLabel.Text = "AAA";
            this.departSecondAirportLabel.Visible = false;
            // 
            // arriveFirstAirportLabel
            // 
            this.arriveFirstAirportLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.arriveFirstAirportLabel.AutoSize = true;
            this.arriveFirstAirportLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.arriveFirstAirportLabel.ForeColor = System.Drawing.Color.White;
            this.arriveFirstAirportLabel.Location = new System.Drawing.Point(148, 108);
            this.arriveFirstAirportLabel.Name = "arriveFirstAirportLabel";
            this.arriveFirstAirportLabel.Size = new System.Drawing.Size(61, 29);
            this.arriveFirstAirportLabel.TabIndex = 97;
            this.arriveFirstAirportLabel.Text = "AAA";
            // 
            // arriveAirportLabel
            // 
            this.arriveAirportLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.arriveAirportLabel.AutoSize = true;
            this.arriveAirportLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.arriveAirportLabel.ForeColor = System.Drawing.Color.White;
            this.arriveAirportLabel.Location = new System.Drawing.Point(148, 261);
            this.arriveAirportLabel.Name = "arriveAirportLabel";
            this.arriveAirportLabel.Size = new System.Drawing.Size(61, 29);
            this.arriveAirportLabel.TabIndex = 98;
            this.arriveAirportLabel.Text = "AAA";
            this.arriveAirportLabel.Visible = false;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::Air3550.Properties.Resources.airplane;
            this.pictureBox1.Location = new System.Drawing.Point(83, 99);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(50, 38);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 99;
            this.pictureBox1.TabStop = false;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = global::Air3550.Properties.Resources.airplane;
            this.pictureBox2.Location = new System.Drawing.Point(83, 252);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(50, 38);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 100;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Visible = false;
            // 
            // legsFirstLabel
            // 
            this.legsFirstLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.legsFirstLabel.AutoSize = true;
            this.legsFirstLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.legsFirstLabel.ForeColor = System.Drawing.Color.White;
            this.legsFirstLabel.Location = new System.Drawing.Point(215, 108);
            this.legsFirstLabel.Name = "legsFirstLabel";
            this.legsFirstLabel.Size = new System.Drawing.Size(114, 29);
            this.legsFirstLabel.TabIndex = 101;
            this.legsFirstLabel.Text = "Nonstop";
            // 
            // legsSecondLabel
            // 
            this.legsSecondLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.legsSecondLabel.AutoSize = true;
            this.legsSecondLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.legsSecondLabel.ForeColor = System.Drawing.Color.White;
            this.legsSecondLabel.Location = new System.Drawing.Point(215, 261);
            this.legsSecondLabel.Name = "legsSecondLabel";
            this.legsSecondLabel.Size = new System.Drawing.Size(114, 29);
            this.legsSecondLabel.TabIndex = 102;
            this.legsSecondLabel.Text = "Nonstop";
            this.legsSecondLabel.Visible = false;
            // 
            // pointsValueLabel
            // 
            this.pointsValueLabel.AutoSize = true;
            this.pointsValueLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.pointsValueLabel.ForeColor = System.Drawing.Color.White;
            this.pointsValueLabel.Location = new System.Drawing.Point(617, 9);
            this.pointsValueLabel.Name = "pointsValueLabel";
            this.pointsValueLabel.Size = new System.Drawing.Size(58, 29);
            this.pointsValueLabel.TabIndex = 104;
            this.pointsValueLabel.Text = "200";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(473, 382);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(28, 29);
            this.label5.TabIndex = 105;
            this.label5.Text = "$";
            // 
            // usePointsCheckBox
            // 
            this.usePointsCheckBox.AutoSize = true;
            this.usePointsCheckBox.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.usePointsCheckBox.ForeColor = System.Drawing.Color.White;
            this.usePointsCheckBox.Location = new System.Drawing.Point(630, 51);
            this.usePointsCheckBox.Name = "usePointsCheckBox";
            this.usePointsCheckBox.Size = new System.Drawing.Size(158, 33);
            this.usePointsCheckBox.TabIndex = 106;
            this.usePointsCheckBox.Text = "Use Points";
            this.usePointsCheckBox.UseVisualStyleBackColor = true;
            this.usePointsCheckBox.CheckedChanged += new System.EventHandler(this.usePointsCheckBox_CheckedChanged);
            // 
            // BookFlight
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.usePointsCheckBox);
            this.Controls.Add(this.pointsValueLabel);
            this.Controls.Add(this.legsSecondLabel);
            this.Controls.Add(this.legsFirstLabel);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.arriveAirportLabel);
            this.Controls.Add(this.arriveFirstAirportLabel);
            this.Controls.Add(this.departSecondAirportLabel);
            this.Controls.Add(this.departFirstAirportLabel);
            this.Controls.Add(this.currentPointsLabel);
            this.Controls.Add(this.finalPriceLabel);
            this.Controls.Add(this.cancelTransactionButton);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.totalPriceLabel);
            this.Controls.Add(this.secondPriceLabel);
            this.Controls.Add(this.firstPriceLabel);
            this.Controls.Add(this.bookFlightsFinalButton);
            this.Controls.Add(this.label5);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "BookFlight";
            this.Text = "BookFlight";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button cancelTransactionButton;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label totalPriceLabel;
        private System.Windows.Forms.Label secondPriceLabel;
        private System.Windows.Forms.Label firstPriceLabel;
        private System.Windows.Forms.Button bookFlightsFinalButton;
        private System.Windows.Forms.Label finalPriceLabel;
        private System.Windows.Forms.Label currentPointsLabel;
        private System.Windows.Forms.Label departFirstAirportLabel;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.Label departSecondAirportLabel;
        private System.Windows.Forms.Label arriveFirstAirportLabel;
        private System.Windows.Forms.Label arriveAirportLabel;
        private System.Windows.Forms.Label legsFirstLabel;
        private System.Windows.Forms.Label legsSecondLabel;
        private System.Windows.Forms.Label pointsValueLabel;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.CheckBox usePointsCheckBox;
    }
}