/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //This is autogenerated code by winforms
    partial class BrowseFlightsTopForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.searchButton = new System.Windows.Forms.Button();
            this.returnDateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.departingDateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.originComboBox = new System.Windows.Forms.ComboBox();
            this.destinationComboBox = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.returnDateLabel = new System.Windows.Forms.Label();
            this.roundTripRadioButton = new System.Windows.Forms.RadioButton();
            this.onewayRadioButton = new System.Windows.Forms.RadioButton();
            this.SuspendLayout();
            // 
            // searchButton
            // 
            this.searchButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.searchButton.BackColor = System.Drawing.Color.Red;
            this.searchButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.searchButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.searchButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.searchButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.searchButton.Location = new System.Drawing.Point(829, 42);
            this.searchButton.Name = "searchButton";
            this.searchButton.Size = new System.Drawing.Size(90, 32);
            this.searchButton.TabIndex = 65;
            this.searchButton.Text = "Search";
            this.searchButton.UseVisualStyleBackColor = false;
            this.searchButton.Click += new System.EventHandler(this.searchButton_Click);
            // 
            // returnDateTimePicker
            // 
            this.returnDateTimePicker.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.returnDateTimePicker.Location = new System.Drawing.Point(563, 48);
            this.returnDateTimePicker.Name = "returnDateTimePicker";
            this.returnDateTimePicker.Size = new System.Drawing.Size(219, 23);
            this.returnDateTimePicker.TabIndex = 66;
            this.returnDateTimePicker.Visible = false;
            // 
            // departingDateTimePicker
            // 
            this.departingDateTimePicker.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.departingDateTimePicker.Location = new System.Drawing.Point(326, 48);
            this.departingDateTimePicker.Name = "departingDateTimePicker";
            this.departingDateTimePicker.Size = new System.Drawing.Size(219, 23);
            this.departingDateTimePicker.TabIndex = 67;
            // 
            // originComboBox
            // 
            this.originComboBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.originComboBox.FormattingEnabled = true;
            this.originComboBox.Location = new System.Drawing.Point(12, 48);
            this.originComboBox.Name = "originComboBox";
            this.originComboBox.Size = new System.Drawing.Size(139, 23);
            this.originComboBox.TabIndex = 68;
            // 
            // destinationComboBox
            // 
            this.destinationComboBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.destinationComboBox.FormattingEnabled = true;
            this.destinationComboBox.Location = new System.Drawing.Point(169, 48);
            this.destinationComboBox.Name = "destinationComboBox";
            this.destinationComboBox.Size = new System.Drawing.Size(139, 23);
            this.destinationComboBox.TabIndex = 69;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(12, 26);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(58, 19);
            this.label1.TabIndex = 70;
            this.label1.Text = "Origin";
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(169, 26);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(103, 19);
            this.label2.TabIndex = 71;
            this.label2.Text = "Destination";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(326, 26);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(136, 19);
            this.label3.TabIndex = 72;
            this.label3.Text = "Departure Date";
            // 
            // returnDateLabel
            // 
            this.returnDateLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.returnDateLabel.AutoSize = true;
            this.returnDateLabel.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.returnDateLabel.ForeColor = System.Drawing.Color.White;
            this.returnDateLabel.Location = new System.Drawing.Point(563, 26);
            this.returnDateLabel.Name = "returnDateLabel";
            this.returnDateLabel.Size = new System.Drawing.Size(109, 19);
            this.returnDateLabel.TabIndex = 73;
            this.returnDateLabel.Text = "Return Date";
            this.returnDateLabel.Visible = false;
            // 
            // roundTripRadioButton
            // 
            this.roundTripRadioButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.roundTripRadioButton.AutoSize = true;
            this.roundTripRadioButton.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.roundTripRadioButton.ForeColor = System.Drawing.Color.White;
            this.roundTripRadioButton.Location = new System.Drawing.Point(706, 12);
            this.roundTripRadioButton.Name = "roundTripRadioButton";
            this.roundTripRadioButton.Size = new System.Drawing.Size(117, 23);
            this.roundTripRadioButton.TabIndex = 74;
            this.roundTripRadioButton.Text = "Round Trip";
            this.roundTripRadioButton.UseVisualStyleBackColor = true;
            this.roundTripRadioButton.CheckedChanged += new System.EventHandler(this.roundTripRadioButton_CheckedChanged);
            // 
            // onewayRadioButton
            // 
            this.onewayRadioButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.onewayRadioButton.AutoSize = true;
            this.onewayRadioButton.Checked = true;
            this.onewayRadioButton.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.onewayRadioButton.ForeColor = System.Drawing.Color.White;
            this.onewayRadioButton.Location = new System.Drawing.Point(829, 12);
            this.onewayRadioButton.Name = "onewayRadioButton";
            this.onewayRadioButton.Size = new System.Drawing.Size(99, 23);
            this.onewayRadioButton.TabIndex = 75;
            this.onewayRadioButton.TabStop = true;
            this.onewayRadioButton.Text = "One Way";
            this.onewayRadioButton.UseVisualStyleBackColor = true;
            this.onewayRadioButton.CheckedChanged += new System.EventHandler(this.onewayRadioButton_CheckedChanged);
            // 
            // BrowseFlightsTopForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.ClientSize = new System.Drawing.Size(940, 102);
            this.Controls.Add(this.onewayRadioButton);
            this.Controls.Add(this.roundTripRadioButton);
            this.Controls.Add(this.returnDateLabel);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.destinationComboBox);
            this.Controls.Add(this.originComboBox);
            this.Controls.Add(this.departingDateTimePicker);
            this.Controls.Add(this.returnDateTimePicker);
            this.Controls.Add(this.searchButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            this.Name = "BrowseFlightsTopForm";
            this.Text = "BrowseFlightsTopForm";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button searchButton;
        private System.Windows.Forms.DateTimePicker returnDateTimePicker;
        private System.Windows.Forms.DateTimePicker departingDateTimePicker;
        private System.Windows.Forms.ComboBox originComboBox;
        private System.Windows.Forms.ComboBox destinationComboBox;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label returnDateLabel;
        public System.Windows.Forms.RadioButton roundTripRadioButton;
        public System.Windows.Forms.RadioButton onewayRadioButton;
    }
}