/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //this is autogenerated code from winforms
    partial class ChangePasswordForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ChangePasswordForm));
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.orginalPasswordTextBox = new System.Windows.Forms.TextBox();
            this.originalPaswordOutline = new System.Windows.Forms.Panel();
            this.label3 = new System.Windows.Forms.Label();
            this.newPasswordTextBox = new System.Windows.Forms.TextBox();
            this.newPasswordOutline = new System.Windows.Forms.Panel();
            this.label4 = new System.Windows.Forms.Label();
            this.confirmPasswordTextBox = new System.Windows.Forms.TextBox();
            this.conFirmPasswordOutline = new System.Windows.Forms.Panel();
            this.saveChangeButton = new System.Windows.Forms.Button();
            this.discardChangesButton = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // pictureBox1
            // 
            this.pictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pictureBox1.Image = global::Air3550.Properties.Resources.airplane;
            this.pictureBox1.Location = new System.Drawing.Point(108, 25);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(147, 139);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label1.Font = new System.Drawing.Font("Tahoma", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label1.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label1.Location = new System.Drawing.Point(37, 167);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(299, 39);
            this.label1.TabIndex = 2;
            this.label1.Text = "Change Password";
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label2.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label2.Location = new System.Drawing.Point(55, 227);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(158, 18);
            this.label2.TabIndex = 52;
            this.label2.Text = "Old Pasword";
            // 
            // orginalPasswordTextBox
            // 
            this.orginalPasswordTextBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.orginalPasswordTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.orginalPasswordTextBox.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.orginalPasswordTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.orginalPasswordTextBox.Location = new System.Drawing.Point(55, 248);
            this.orginalPasswordTextBox.Name = "orginalPasswordTextBox";
            this.orginalPasswordTextBox.Size = new System.Drawing.Size(262, 33);
            this.orginalPasswordTextBox.TabIndex = 51;
            // 
            // originalPaswordOutline
            // 
            this.originalPaswordOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.originalPaswordOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.originalPaswordOutline.Location = new System.Drawing.Point(52, 246);
            this.originalPaswordOutline.Name = "originalPaswordOutline";
            this.originalPaswordOutline.Padding = new System.Windows.Forms.Padding(2);
            this.originalPaswordOutline.Size = new System.Drawing.Size(269, 38);
            this.originalPaswordOutline.TabIndex = 53;
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label3.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label3.Location = new System.Drawing.Point(55, 292);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(158, 18);
            this.label3.TabIndex = 55;
            this.label3.Text = "New Password";
            // 
            // newPasswordTextBox
            // 
            this.newPasswordTextBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.newPasswordTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.newPasswordTextBox.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.newPasswordTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.newPasswordTextBox.Location = new System.Drawing.Point(55, 313);
            this.newPasswordTextBox.Name = "newPasswordTextBox";
            this.newPasswordTextBox.Size = new System.Drawing.Size(262, 33);
            this.newPasswordTextBox.TabIndex = 54;
            // 
            // newPasswordOutline
            // 
            this.newPasswordOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.newPasswordOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.newPasswordOutline.Location = new System.Drawing.Point(52, 311);
            this.newPasswordOutline.Name = "newPasswordOutline";
            this.newPasswordOutline.Padding = new System.Windows.Forms.Padding(2);
            this.newPasswordOutline.Size = new System.Drawing.Size(269, 38);
            this.newPasswordOutline.TabIndex = 56;
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label4.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label4.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label4.Location = new System.Drawing.Point(52, 363);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(158, 18);
            this.label4.TabIndex = 58;
            this.label4.Text = "Confirm Password";
            // 
            // confirmPasswordTextBox
            // 
            this.confirmPasswordTextBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.confirmPasswordTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.confirmPasswordTextBox.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.confirmPasswordTextBox.ForeColor = System.Drawing.SystemColors.WindowText;
            this.confirmPasswordTextBox.Location = new System.Drawing.Point(52, 384);
            this.confirmPasswordTextBox.Name = "confirmPasswordTextBox";
            this.confirmPasswordTextBox.Size = new System.Drawing.Size(262, 33);
            this.confirmPasswordTextBox.TabIndex = 57;
            // 
            // conFirmPasswordOutline
            // 
            this.conFirmPasswordOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.conFirmPasswordOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.conFirmPasswordOutline.Location = new System.Drawing.Point(49, 382);
            this.conFirmPasswordOutline.Name = "conFirmPasswordOutline";
            this.conFirmPasswordOutline.Padding = new System.Windows.Forms.Padding(2);
            this.conFirmPasswordOutline.Size = new System.Drawing.Size(269, 38);
            this.conFirmPasswordOutline.TabIndex = 59;
            // 
            // saveChangeButton
            // 
            this.saveChangeButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.saveChangeButton.BackColor = System.Drawing.Color.Red;
            this.saveChangeButton.FlatAppearance.BorderSize = 0;
            this.saveChangeButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.saveChangeButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.saveChangeButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.saveChangeButton.Location = new System.Drawing.Point(28, 448);
            this.saveChangeButton.Name = "saveChangeButton";
            this.saveChangeButton.Size = new System.Drawing.Size(141, 40);
            this.saveChangeButton.TabIndex = 65;
            this.saveChangeButton.Text = "Save Changes";
            this.saveChangeButton.UseVisualStyleBackColor = false;
            this.saveChangeButton.Click += new System.EventHandler(this.saveChangeButton_Click);
            // 
            // discardChangesButton
            // 
            this.discardChangesButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.discardChangesButton.BackColor = System.Drawing.Color.Red;
            this.discardChangesButton.FlatAppearance.BorderSize = 0;
            this.discardChangesButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.discardChangesButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.discardChangesButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.discardChangesButton.Location = new System.Drawing.Point(204, 448);
            this.discardChangesButton.Name = "discardChangesButton";
            this.discardChangesButton.Size = new System.Drawing.Size(141, 40);
            this.discardChangesButton.TabIndex = 66;
            this.discardChangesButton.Text = "Discard";
            this.discardChangesButton.UseVisualStyleBackColor = false;
            this.discardChangesButton.Click += new System.EventHandler(this.discardChangesButton_Click);
            // 
            // ChangePasswordForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.ClientSize = new System.Drawing.Size(372, 511);
            this.Controls.Add(this.discardChangesButton);
            this.Controls.Add(this.saveChangeButton);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.confirmPasswordTextBox);
            this.Controls.Add(this.conFirmPasswordOutline);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.newPasswordTextBox);
            this.Controls.Add(this.newPasswordOutline);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.orginalPasswordTextBox);
            this.Controls.Add(this.originalPaswordOutline);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pictureBox1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "ChangePasswordForm";
            this.Text = "ChangePasswordForm";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox orginalPasswordTextBox;
        private System.Windows.Forms.Panel originalPaswordOutline;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox newPasswordTextBox;
        private System.Windows.Forms.Panel newPasswordOutline;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox confirmPasswordTextBox;
        private System.Windows.Forms.Panel conFirmPasswordOutline;
        private System.Windows.Forms.Button saveChangeButton;
        private System.Windows.Forms.Button discardChangesButton;
    }
}