/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //This is autogenerated code from winforms
    partial class CreateAccountForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CreateAccountForm));
            this.label2 = new System.Windows.Forms.Label();
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.nameText = new System.Windows.Forms.TextBox();
            this.addressText = new System.Windows.Forms.TextBox();
            this.phoneText = new System.Windows.Forms.TextBox();
            this.ageText = new System.Windows.Forms.TextBox();
            this.passwordText = new System.Windows.Forms.TextBox();
            this.billingText = new System.Windows.Forms.TextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.nameOutline = new System.Windows.Forms.Panel();
            this.ageOutline = new System.Windows.Forms.Panel();
            this.billingOutline = new System.Windows.Forms.Panel();
            this.addressOutline = new System.Windows.Forms.Panel();
            this.numberOutline = new System.Windows.Forms.Panel();
            this.passwordOutline = new System.Windows.Forms.Panel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.lastNameText = new System.Windows.Forms.TextBox();
            this.lastNameOutline = new System.Windows.Forms.Panel();
            this.confirmPasswordText = new System.Windows.Forms.TextBox();
            this.confirmPasswordOutline = new System.Windows.Forms.Panel();
            this.label8 = new System.Windows.Forms.Label();
            this.confirmPasswordLabel = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.Font = new System.Drawing.Font("Tahoma", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label2.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label2.Location = new System.Drawing.Point(292, 63);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(370, 39);
            this.label2.TabIndex = 10;
            this.label2.Text = "Create a New Account";
            // 
            // button2
            // 
            this.button2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.button2.BackColor = System.Drawing.Color.Red;
            this.button2.FlatAppearance.BorderSize = 0;
            this.button2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button2.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.button2.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.button2.Location = new System.Drawing.Point(302, 425);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(316, 40);
            this.button2.TabIndex = 11;
            this.button2.Text = "Create Account";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.button3.BackColor = System.Drawing.Color.Red;
            this.button3.FlatAppearance.BorderSize = 0;
            this.button3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button3.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.button3.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.button3.Location = new System.Drawing.Point(767, 470);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(144, 31);
            this.button3.TabIndex = 12;
            this.button3.Text = "Exit";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // nameText
            // 
            this.nameText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.nameText.BackColor = System.Drawing.SystemColors.Window;
            this.nameText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.nameText.ForeColor = System.Drawing.SystemColors.WindowText;
            this.nameText.Location = new System.Drawing.Point(146, 161);
            this.nameText.Name = "nameText";
            this.nameText.Size = new System.Drawing.Size(262, 33);
            this.nameText.TabIndex = 13;
            this.nameText.TextChanged += new System.EventHandler(this.nameText_TextChanged);
            // 
            // addressText
            // 
            this.addressText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.addressText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.addressText.Location = new System.Drawing.Point(146, 367);
            this.addressText.Name = "addressText";
            this.addressText.Size = new System.Drawing.Size(262, 33);
            this.addressText.TabIndex = 14;
            // 
            // phoneText
            // 
            this.phoneText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.phoneText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.phoneText.Location = new System.Drawing.Point(146, 305);
            this.phoneText.Name = "phoneText";
            this.phoneText.Size = new System.Drawing.Size(262, 33);
            this.phoneText.TabIndex = 15;
            // 
            // ageText
            // 
            this.ageText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.ageText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.ageText.Location = new System.Drawing.Point(515, 161);
            this.ageText.Name = "ageText";
            this.ageText.Size = new System.Drawing.Size(262, 33);
            this.ageText.TabIndex = 16;
            // 
            // passwordText
            // 
            this.passwordText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.passwordText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.passwordText.Location = new System.Drawing.Point(515, 305);
            this.passwordText.Name = "passwordText";
            this.passwordText.Size = new System.Drawing.Size(262, 33);
            this.passwordText.TabIndex = 17;
            this.passwordText.UseSystemPasswordChar = true;
            // 
            // billingText
            // 
            this.billingText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.billingText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.billingText.Location = new System.Drawing.Point(515, 234);
            this.billingText.Name = "billingText";
            this.billingText.Size = new System.Drawing.Size(262, 33);
            this.billingText.TabIndex = 18;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pictureBox1.Image = global::Air3550.Properties.Resources.airplane;
            this.pictureBox1.Location = new System.Drawing.Point(232, 63);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(54, 45);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 19;
            this.pictureBox1.TabStop = false;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label1.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label1.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label1.Location = new System.Drawing.Point(146, 140);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(158, 18);
            this.label1.TabIndex = 20;
            this.label1.Text = "First Name";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label3.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label3.Location = new System.Drawing.Point(146, 346);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(158, 18);
            this.label3.TabIndex = 21;
            this.label3.Text = "Address";
            // 
            // label4
            // 
            this.label4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label4.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label4.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label4.Location = new System.Drawing.Point(146, 284);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(158, 18);
            this.label4.TabIndex = 22;
            this.label4.Text = "Phone Number";
            // 
            // label5
            // 
            this.label5.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label5.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label5.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label5.Location = new System.Drawing.Point(515, 284);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(158, 18);
            this.label5.TabIndex = 23;
            this.label5.Text = "Password";
            // 
            // label6
            // 
            this.label6.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label6.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label6.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label6.Location = new System.Drawing.Point(515, 213);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(158, 18);
            this.label6.TabIndex = 24;
            this.label6.Text = "Billing Information";
            // 
            // label7
            // 
            this.label7.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label7.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label7.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label7.Location = new System.Drawing.Point(515, 140);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(158, 18);
            this.label7.TabIndex = 25;
            this.label7.Text = "Age";
            // 
            // nameOutline
            // 
            this.nameOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.nameOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.nameOutline.Location = new System.Drawing.Point(143, 159);
            this.nameOutline.Name = "nameOutline";
            this.nameOutline.Padding = new System.Windows.Forms.Padding(2);
            this.nameOutline.Size = new System.Drawing.Size(269, 38);
            this.nameOutline.TabIndex = 26;
            // 
            // ageOutline
            // 
            this.ageOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.ageOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.ageOutline.Location = new System.Drawing.Point(511, 159);
            this.ageOutline.Name = "ageOutline";
            this.ageOutline.Padding = new System.Windows.Forms.Padding(2);
            this.ageOutline.Size = new System.Drawing.Size(269, 38);
            this.ageOutline.TabIndex = 27;
            // 
            // billingOutline
            // 
            this.billingOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.billingOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.billingOutline.Location = new System.Drawing.Point(512, 231);
            this.billingOutline.Name = "billingOutline";
            this.billingOutline.Padding = new System.Windows.Forms.Padding(2);
            this.billingOutline.Size = new System.Drawing.Size(269, 38);
            this.billingOutline.TabIndex = 28;
            // 
            // addressOutline
            // 
            this.addressOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.addressOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.addressOutline.Location = new System.Drawing.Point(143, 365);
            this.addressOutline.Name = "addressOutline";
            this.addressOutline.Padding = new System.Windows.Forms.Padding(2);
            this.addressOutline.Size = new System.Drawing.Size(269, 38);
            this.addressOutline.TabIndex = 29;
            // 
            // numberOutline
            // 
            this.numberOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numberOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.numberOutline.Location = new System.Drawing.Point(143, 302);
            this.numberOutline.Name = "numberOutline";
            this.numberOutline.Padding = new System.Windows.Forms.Padding(2);
            this.numberOutline.Size = new System.Drawing.Size(269, 38);
            this.numberOutline.TabIndex = 29;
            // 
            // passwordOutline
            // 
            this.passwordOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.passwordOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.passwordOutline.Location = new System.Drawing.Point(512, 303);
            this.passwordOutline.Name = "passwordOutline";
            this.passwordOutline.Padding = new System.Windows.Forms.Padding(2);
            this.passwordOutline.Size = new System.Drawing.Size(269, 38);
            this.passwordOutline.TabIndex = 30;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pictureBox2.Image = global::Air3550.Properties.Resources.eye;
            this.pictureBox2.Location = new System.Drawing.Point(783, 303);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(48, 38);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 31;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            // 
            // lastNameText
            // 
            this.lastNameText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lastNameText.BackColor = System.Drawing.SystemColors.Window;
            this.lastNameText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lastNameText.ForeColor = System.Drawing.SystemColors.WindowText;
            this.lastNameText.Location = new System.Drawing.Point(146, 231);
            this.lastNameText.Name = "lastNameText";
            this.lastNameText.Size = new System.Drawing.Size(262, 33);
            this.lastNameText.TabIndex = 32;
            // 
            // lastNameOutline
            // 
            this.lastNameOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lastNameOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.lastNameOutline.Location = new System.Drawing.Point(143, 229);
            this.lastNameOutline.Name = "lastNameOutline";
            this.lastNameOutline.Padding = new System.Windows.Forms.Padding(2);
            this.lastNameOutline.Size = new System.Drawing.Size(269, 38);
            this.lastNameOutline.TabIndex = 33;
            // 
            // confirmPasswordText
            // 
            this.confirmPasswordText.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.confirmPasswordText.BackColor = System.Drawing.SystemColors.Window;
            this.confirmPasswordText.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.confirmPasswordText.ForeColor = System.Drawing.SystemColors.WindowText;
            this.confirmPasswordText.Location = new System.Drawing.Point(515, 369);
            this.confirmPasswordText.Name = "confirmPasswordText";
            this.confirmPasswordText.Size = new System.Drawing.Size(262, 33);
            this.confirmPasswordText.TabIndex = 34;
            this.confirmPasswordText.UseSystemPasswordChar = true;
            // 
            // confirmPasswordOutline
            // 
            this.confirmPasswordOutline.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.confirmPasswordOutline.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.confirmPasswordOutline.Location = new System.Drawing.Point(512, 367);
            this.confirmPasswordOutline.Name = "confirmPasswordOutline";
            this.confirmPasswordOutline.Padding = new System.Windows.Forms.Padding(2);
            this.confirmPasswordOutline.Size = new System.Drawing.Size(269, 38);
            this.confirmPasswordOutline.TabIndex = 35;
            // 
            // label8
            // 
            this.label8.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label8.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label8.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label8.Location = new System.Drawing.Point(146, 208);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(158, 18);
            this.label8.TabIndex = 36;
            this.label8.Text = "Last Name";
            // 
            // confirmPasswordLabel
            // 
            this.confirmPasswordLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.confirmPasswordLabel.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.confirmPasswordLabel.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.confirmPasswordLabel.Location = new System.Drawing.Point(512, 346);
            this.confirmPasswordLabel.Name = "confirmPasswordLabel";
            this.confirmPasswordLabel.Size = new System.Drawing.Size(158, 18);
            this.confirmPasswordLabel.TabIndex = 37;
            this.confirmPasswordLabel.Text = "Confirm Password";
            // 
            // CreateAccountForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.ClientSize = new System.Drawing.Size(923, 513);
            this.Controls.Add(this.confirmPasswordLabel);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.confirmPasswordText);
            this.Controls.Add(this.confirmPasswordOutline);
            this.Controls.Add(this.lastNameText);
            this.Controls.Add(this.lastNameOutline);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.billingText);
            this.Controls.Add(this.passwordText);
            this.Controls.Add(this.ageText);
            this.Controls.Add(this.phoneText);
            this.Controls.Add(this.addressText);
            this.Controls.Add(this.nameText);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.nameOutline);
            this.Controls.Add(this.ageOutline);
            this.Controls.Add(this.billingOutline);
            this.Controls.Add(this.addressOutline);
            this.Controls.Add(this.numberOutline);
            this.Controls.Add(this.passwordOutline);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(939, 552);
            this.Name = "CreateAccountForm";
            this.Text = "Air3550-CreateAccount";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.TextBox nameText;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox ageText;
        private System.Windows.Forms.TextBox addressText;
        private System.Windows.Forms.TextBox billingText;
        private System.Windows.Forms.TextBox phoneText;
        private System.Windows.Forms.TextBox passwordText;
        private System.Windows.Forms.Panel nameOutline;
        private System.Windows.Forms.Panel ageOutline;
        private System.Windows.Forms.Panel billingOutline;
        private System.Windows.Forms.Panel addressOutline;
        private System.Windows.Forms.Panel numberOutline;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.Panel passwordOutline;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.TextBox lastNameText;
        private System.Windows.Forms.Panel lastNameOutline;
        private System.Windows.Forms.TextBox confirmPasswordText;
        private System.Windows.Forms.Panel confirmPasswordOutline;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label confirmPasswordLabel;
    }
}