/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //this is autogenerated code from winforms
    partial class CustomerForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CustomerForm));
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.customerSideMenuPanel = new System.Windows.Forms.Panel();
            this.customerExitButton = new System.Windows.Forms.Button();
            this.flightHistoryButton = new System.Windows.Forms.Button();
            this.browseFlightsButton = new System.Windows.Forms.Button();
            this.accountInfoButton = new System.Windows.Forms.Button();
            this.customerSidePanelTop = new System.Windows.Forms.Panel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.topBarPanel = new System.Windows.Forms.Panel();
            this.mainPanel = new System.Windows.Forms.Panel();
            this.customerLogOutButton = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.customerSideMenuPanel.SuspendLayout();
            this.customerSidePanelTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::Air3550.Properties.Resources.Loginicon;
            this.pictureBox1.Location = new System.Drawing.Point(12, 105);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(48, 30);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label2.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label2.Location = new System.Drawing.Point(56, 113);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(204, 28);
            this.label2.TabIndex = 11;
            this.label2.Text = "This is where ID will be";
            // 
            // customerSideMenuPanel
            // 
            this.customerSideMenuPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(6)))), ((int)(((byte)(18)))));
            this.customerSideMenuPanel.Controls.Add(this.customerExitButton);
            this.customerSideMenuPanel.Controls.Add(this.flightHistoryButton);
            this.customerSideMenuPanel.Controls.Add(this.browseFlightsButton);
            this.customerSideMenuPanel.Controls.Add(this.accountInfoButton);
            this.customerSideMenuPanel.Controls.Add(this.customerSidePanelTop);
            this.customerSideMenuPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.customerSideMenuPanel.Location = new System.Drawing.Point(0, 0);
            this.customerSideMenuPanel.Name = "customerSideMenuPanel";
            this.customerSideMenuPanel.Size = new System.Drawing.Size(260, 712);
            this.customerSideMenuPanel.TabIndex = 12;
            // 
            // customerExitButton
            // 
            this.customerExitButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.customerExitButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.customerExitButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.customerExitButton.Font = new System.Drawing.Font("Tahoma", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.customerExitButton.ForeColor = System.Drawing.Color.White;
            this.customerExitButton.Location = new System.Drawing.Point(0, 564);
            this.customerExitButton.Name = "customerExitButton";
            this.customerExitButton.Size = new System.Drawing.Size(260, 148);
            this.customerExitButton.TabIndex = 4;
            this.customerExitButton.Text = "Exit";
            this.customerExitButton.UseVisualStyleBackColor = true;
            this.customerExitButton.Click += new System.EventHandler(this.customerExitButton_Click);
            // 
            // flightHistoryButton
            // 
            this.flightHistoryButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.flightHistoryButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.flightHistoryButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.flightHistoryButton.Font = new System.Drawing.Font("Tahoma", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.flightHistoryButton.ForeColor = System.Drawing.Color.White;
            this.flightHistoryButton.Location = new System.Drawing.Point(0, 423);
            this.flightHistoryButton.Name = "flightHistoryButton";
            this.flightHistoryButton.Size = new System.Drawing.Size(260, 141);
            this.flightHistoryButton.TabIndex = 3;
            this.flightHistoryButton.Text = "View Flight History";
            this.flightHistoryButton.UseVisualStyleBackColor = true;
            this.flightHistoryButton.Click += new System.EventHandler(this.flightHistoryButton_Click);
            // 
            // browseFlightsButton
            // 
            this.browseFlightsButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.browseFlightsButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.browseFlightsButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.browseFlightsButton.Font = new System.Drawing.Font("Tahoma", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.browseFlightsButton.ForeColor = System.Drawing.Color.White;
            this.browseFlightsButton.Location = new System.Drawing.Point(0, 282);
            this.browseFlightsButton.Name = "browseFlightsButton";
            this.browseFlightsButton.Size = new System.Drawing.Size(260, 141);
            this.browseFlightsButton.TabIndex = 2;
            this.browseFlightsButton.Text = "Browse Flights";
            this.browseFlightsButton.UseVisualStyleBackColor = true;
            this.browseFlightsButton.Click += new System.EventHandler(this.browseFlightsButton_Click);
            // 
            // accountInfoButton
            // 
            this.accountInfoButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.accountInfoButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.accountInfoButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.accountInfoButton.Font = new System.Drawing.Font("Tahoma", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.accountInfoButton.ForeColor = System.Drawing.Color.White;
            this.accountInfoButton.Location = new System.Drawing.Point(0, 141);
            this.accountInfoButton.Name = "accountInfoButton";
            this.accountInfoButton.Size = new System.Drawing.Size(260, 141);
            this.accountInfoButton.TabIndex = 1;
            this.accountInfoButton.Text = "Account Info";
            this.accountInfoButton.UseVisualStyleBackColor = true;
            this.accountInfoButton.Click += new System.EventHandler(this.accountInfoButton_Click);
            // 
            // customerSidePanelTop
            // 
            this.customerSidePanelTop.Controls.Add(this.customerLogOutButton);
            this.customerSidePanelTop.Controls.Add(this.pictureBox2);
            this.customerSidePanelTop.Controls.Add(this.pictureBox1);
            this.customerSidePanelTop.Controls.Add(this.label2);
            this.customerSidePanelTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.customerSidePanelTop.Location = new System.Drawing.Point(0, 0);
            this.customerSidePanelTop.Name = "customerSidePanelTop";
            this.customerSidePanelTop.Size = new System.Drawing.Size(260, 141);
            this.customerSidePanelTop.TabIndex = 0;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = global::Air3550.Properties.Resources.airplane;
            this.pictureBox2.Location = new System.Drawing.Point(167, 12);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(87, 76);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 12;
            this.pictureBox2.TabStop = false;
            // 
            // topBarPanel
            // 
            this.topBarPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.topBarPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.topBarPanel.Location = new System.Drawing.Point(260, 0);
            this.topBarPanel.Name = "topBarPanel";
            this.topBarPanel.Size = new System.Drawing.Size(956, 141);
            this.topBarPanel.TabIndex = 13;
            // 
            // mainPanel
            // 
            this.mainPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.mainPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainPanel.Location = new System.Drawing.Point(260, 141);
            this.mainPanel.MinimumSize = new System.Drawing.Size(956, 571);
            this.mainPanel.Name = "mainPanel";
            this.mainPanel.Size = new System.Drawing.Size(956, 571);
            this.mainPanel.TabIndex = 14;
            // 
            // customerLogOutButton
            // 
            this.customerLogOutButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.customerLogOutButton.BackColor = System.Drawing.Color.Red;
            this.customerLogOutButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.customerLogOutButton.FlatAppearance.BorderSize = 0;
            this.customerLogOutButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.customerLogOutButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.customerLogOutButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.customerLogOutButton.Location = new System.Drawing.Point(12, 12);
            this.customerLogOutButton.Name = "customerLogOutButton";
            this.customerLogOutButton.Size = new System.Drawing.Size(105, 40);
            this.customerLogOutButton.TabIndex = 92;
            this.customerLogOutButton.TabStop = false;
            this.customerLogOutButton.Text = "Logout";
            this.customerLogOutButton.UseVisualStyleBackColor = false;
            this.customerLogOutButton.Click += new System.EventHandler(this.customerLogOutButton_Click);
            // 
            // CustomerForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1216, 712);
            this.Controls.Add(this.mainPanel);
            this.Controls.Add(this.topBarPanel);
            this.Controls.Add(this.customerSideMenuPanel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(1232, 751);
            this.Name = "CustomerForm";
            this.Text = "Air3550-Customer";
            this.Load += new System.EventHandler(this.CustomerForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.customerSideMenuPanel.ResumeLayout(false);
            this.customerSidePanelTop.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Panel customerSideMenuPanel;
        public System.Windows.Forms.Button flightHistoryButton;
        private System.Windows.Forms.Button browseFlightsButton;
        private System.Windows.Forms.Button accountInfoButton;
        private System.Windows.Forms.Panel customerSidePanelTop;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.Panel topBarPanel;
        private System.Windows.Forms.Panel mainPanel;
        private System.Windows.Forms.Button customerExitButton;
        public System.Windows.Forms.Button customerLogOutButton;
    }
}