/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //This is autogenerated from winforms
    partial class FlightHistoryMainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.pastFlowLayoutPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.currentFlowLayoutPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.pastLabel = new System.Windows.Forms.Label();
            this.currentLabel = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // pastFlowLayoutPanel
            // 
            this.pastFlowLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.pastFlowLayoutPanel.AutoScroll = true;
            this.pastFlowLayoutPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.pastFlowLayoutPanel.Location = new System.Drawing.Point(12, 41);
            this.pastFlowLayoutPanel.Name = "pastFlowLayoutPanel";
            this.pastFlowLayoutPanel.Size = new System.Drawing.Size(404, 479);
            this.pastFlowLayoutPanel.TabIndex = 0;
            this.pastFlowLayoutPanel.WrapContents = false;
            this.pastFlowLayoutPanel.Paint += new System.Windows.Forms.PaintEventHandler(this.pastFlowLayoutPanel_Paint);
            // 
            // currentFlowLayoutPanel
            // 
            this.currentFlowLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.currentFlowLayoutPanel.AutoScroll = true;
            this.currentFlowLayoutPanel.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.currentFlowLayoutPanel.Location = new System.Drawing.Point(524, 40);
            this.currentFlowLayoutPanel.Name = "currentFlowLayoutPanel";
            this.currentFlowLayoutPanel.Size = new System.Drawing.Size(404, 479);
            this.currentFlowLayoutPanel.TabIndex = 1;
            this.currentFlowLayoutPanel.WrapContents = false;
            // 
            // pastLabel
            // 
            this.pastLabel.AutoSize = true;
            this.pastLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.pastLabel.ForeColor = System.Drawing.Color.White;
            this.pastLabel.Location = new System.Drawing.Point(12, 9);
            this.pastLabel.Name = "pastLabel";
            this.pastLabel.Size = new System.Drawing.Size(152, 29);
            this.pastLabel.TabIndex = 76;
            this.pastLabel.Text = "Past Flights";
            // 
            // currentLabel
            // 
            this.currentLabel.AutoSize = true;
            this.currentLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.currentLabel.ForeColor = System.Drawing.Color.White;
            this.currentLabel.Location = new System.Drawing.Point(524, 9);
            this.currentLabel.Name = "currentLabel";
            this.currentLabel.Size = new System.Drawing.Size(178, 29);
            this.currentLabel.TabIndex = 77;
            this.currentLabel.Text = "Future Flights";
            // 
            // FlightHistoryMainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.ClientSize = new System.Drawing.Size(940, 532);
            this.Controls.Add(this.currentLabel);
            this.Controls.Add(this.pastLabel);
            this.Controls.Add(this.currentFlowLayoutPanel);
            this.Controls.Add(this.pastFlowLayoutPanel);
            this.Name = "FlightHistoryMainForm";
            this.Text = "FlightHistoryMainForm";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        public System.Windows.Forms.FlowLayoutPanel pastFlowLayoutPanel;
        public System.Windows.Forms.FlowLayoutPanel currentFlowLayoutPanel;
        public System.Windows.Forms.Label pastLabel;
        public System.Windows.Forms.Label currentLabel;
    }
}