/*
 Air 3550 Project Team 7

This program is a basic flight reservation system for a fake airline company
It allows customers to book, manage, cancel, and browse flights within a database.
It also allows employee accounts to update and manage flights and view business statistics.

Written by: Harrison Kania, Tyler Ehlert, Daniel Wellons
For EECS3550-001 Software Engineering, Instructor: Dr. Thomas 
 */
namespace Air3550
{
    //this is autogenerated by winforms
    partial class LoadEngineerForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoadEngineerForm));
            this.panel1 = new System.Windows.Forms.Panel();
            this.loadEngineerExitButton = new System.Windows.Forms.Button();
            this.panel2 = new System.Windows.Forms.Panel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.panel3 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.destinationComboBox = new System.Windows.Forms.ComboBox();
            this.originComboBox = new System.Windows.Forms.ComboBox();
            this.addNewFlightButton = new System.Windows.Forms.Button();
            this.browseFlightsMarketingButton = new System.Windows.Forms.Button();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.destinationEngineerLabel = new System.Windows.Forms.Label();
            this.originEngineerLabel = new System.Windows.Forms.Label();
            this.dateEngineerLabel = new System.Windows.Forms.Label();
            this.flightTimeEngineerLabel = new System.Windows.Forms.Label();
            this.loadEngineerLogOutButton = new System.Windows.Forms.Button();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(6)))), ((int)(((byte)(18)))));
            this.panel1.Controls.Add(this.loadEngineerExitButton);
            this.panel1.Controls.Add(this.panel2);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(260, 712);
            this.panel1.TabIndex = 0;
            // 
            // loadEngineerExitButton
            // 
            this.loadEngineerExitButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.loadEngineerExitButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.loadEngineerExitButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.loadEngineerExitButton.Font = new System.Drawing.Font("Tahoma", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.loadEngineerExitButton.ForeColor = System.Drawing.Color.White;
            this.loadEngineerExitButton.Location = new System.Drawing.Point(0, 141);
            this.loadEngineerExitButton.Name = "loadEngineerExitButton";
            this.loadEngineerExitButton.Size = new System.Drawing.Size(260, 148);
            this.loadEngineerExitButton.TabIndex = 8;
            this.loadEngineerExitButton.Text = "Exit";
            this.loadEngineerExitButton.UseVisualStyleBackColor = true;
            this.loadEngineerExitButton.Click += new System.EventHandler(this.accountantExitButton_Click);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.loadEngineerLogOutButton);
            this.panel2.Controls.Add(this.pictureBox2);
            this.panel2.Controls.Add(this.pictureBox1);
            this.panel2.Controls.Add(this.label2);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(260, 141);
            this.panel2.TabIndex = 0;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = global::Air3550.Properties.Resources.airplane;
            this.pictureBox2.Location = new System.Drawing.Point(167, 12);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(87, 76);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 24;
            this.pictureBox2.TabStop = false;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::Air3550.Properties.Resources.Loginicon;
            this.pictureBox1.Location = new System.Drawing.Point(6, 99);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(48, 30);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 22;
            this.pictureBox1.TabStop = false;
            // 
            // label2
            // 
            this.label2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label2.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label2.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label2.Location = new System.Drawing.Point(50, 107);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(204, 28);
            this.label2.TabIndex = 23;
            this.label2.Text = "Load Engineer";
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.panel3.Controls.Add(this.label1);
            this.panel3.Controls.Add(this.label3);
            this.panel3.Controls.Add(this.destinationComboBox);
            this.panel3.Controls.Add(this.originComboBox);
            this.panel3.Controls.Add(this.addNewFlightButton);
            this.panel3.Controls.Add(this.browseFlightsMarketingButton);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel3.Location = new System.Drawing.Point(260, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(956, 141);
            this.panel3.TabIndex = 1;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(471, 17);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(103, 19);
            this.label1.TabIndex = 103;
            this.label1.Text = "Destination";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(314, 17);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(58, 19);
            this.label3.TabIndex = 102;
            this.label3.Text = "Origin";
            // 
            // destinationComboBox
            // 
            this.destinationComboBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.destinationComboBox.FormattingEnabled = true;
            this.destinationComboBox.Location = new System.Drawing.Point(471, 39);
            this.destinationComboBox.Name = "destinationComboBox";
            this.destinationComboBox.Size = new System.Drawing.Size(139, 23);
            this.destinationComboBox.TabIndex = 101;
            // 
            // originComboBox
            // 
            this.originComboBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.originComboBox.FormattingEnabled = true;
            this.originComboBox.Location = new System.Drawing.Point(314, 39);
            this.originComboBox.Name = "originComboBox";
            this.originComboBox.Size = new System.Drawing.Size(139, 23);
            this.originComboBox.TabIndex = 100;
            // 
            // addNewFlightButton
            // 
            this.addNewFlightButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.addNewFlightButton.BackColor = System.Drawing.Color.Red;
            this.addNewFlightButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.addNewFlightButton.FlatAppearance.BorderSize = 0;
            this.addNewFlightButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.addNewFlightButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.addNewFlightButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.addNewFlightButton.Location = new System.Drawing.Point(668, 81);
            this.addNewFlightButton.Name = "addNewFlightButton";
            this.addNewFlightButton.Size = new System.Drawing.Size(237, 40);
            this.addNewFlightButton.TabIndex = 95;
            this.addNewFlightButton.TabStop = false;
            this.addNewFlightButton.Text = "Add New Route";
            this.addNewFlightButton.UseVisualStyleBackColor = false;
            this.addNewFlightButton.Click += new System.EventHandler(this.addNewFlightButton_Click);
            // 
            // browseFlightsMarketingButton
            // 
            this.browseFlightsMarketingButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.browseFlightsMarketingButton.BackColor = System.Drawing.Color.Red;
            this.browseFlightsMarketingButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.browseFlightsMarketingButton.FlatAppearance.BorderSize = 0;
            this.browseFlightsMarketingButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.browseFlightsMarketingButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.browseFlightsMarketingButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.browseFlightsMarketingButton.Location = new System.Drawing.Point(305, 81);
            this.browseFlightsMarketingButton.Name = "browseFlightsMarketingButton";
            this.browseFlightsMarketingButton.Size = new System.Drawing.Size(316, 40);
            this.browseFlightsMarketingButton.TabIndex = 91;
            this.browseFlightsMarketingButton.TabStop = false;
            this.browseFlightsMarketingButton.Text = "Browse Routes";
            this.browseFlightsMarketingButton.UseVisualStyleBackColor = false;
            this.browseFlightsMarketingButton.Click += new System.EventHandler(this.browseFlightsMarketingButton_Click);
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.flowLayoutPanel1.AutoScroll = true;
            this.flowLayoutPanel1.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(266, 184);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(938, 516);
            this.flowLayoutPanel1.TabIndex = 2;
            this.flowLayoutPanel1.WrapContents = false;
            // 
            // destinationEngineerLabel
            // 
            this.destinationEngineerLabel.AutoSize = true;
            this.destinationEngineerLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.destinationEngineerLabel.ForeColor = System.Drawing.Color.White;
            this.destinationEngineerLabel.Location = new System.Drawing.Point(382, 152);
            this.destinationEngineerLabel.Name = "destinationEngineerLabel";
            this.destinationEngineerLabel.Size = new System.Drawing.Size(150, 29);
            this.destinationEngineerLabel.TabIndex = 99;
            this.destinationEngineerLabel.Text = "Destination";
            this.destinationEngineerLabel.UseMnemonic = false;
            // 
            // originEngineerLabel
            // 
            this.originEngineerLabel.AutoSize = true;
            this.originEngineerLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.originEngineerLabel.ForeColor = System.Drawing.Color.White;
            this.originEngineerLabel.Location = new System.Drawing.Point(266, 152);
            this.originEngineerLabel.Name = "originEngineerLabel";
            this.originEngineerLabel.Size = new System.Drawing.Size(85, 29);
            this.originEngineerLabel.TabIndex = 98;
            this.originEngineerLabel.Text = "Origin";
            this.originEngineerLabel.UseMnemonic = false;
            // 
            // dateEngineerLabel
            // 
            this.dateEngineerLabel.AutoSize = true;
            this.dateEngineerLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.dateEngineerLabel.ForeColor = System.Drawing.Color.White;
            this.dateEngineerLabel.Location = new System.Drawing.Point(538, 152);
            this.dateEngineerLabel.Name = "dateEngineerLabel";
            this.dateEngineerLabel.Size = new System.Drawing.Size(175, 29);
            this.dateEngineerLabel.TabIndex = 97;
            this.dateEngineerLabel.Text = "Date of Flight";
            this.dateEngineerLabel.UseMnemonic = false;
            // 
            // flightTimeEngineerLabel
            // 
            this.flightTimeEngineerLabel.AutoSize = true;
            this.flightTimeEngineerLabel.Font = new System.Drawing.Font("Tahoma", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.flightTimeEngineerLabel.ForeColor = System.Drawing.Color.White;
            this.flightTimeEngineerLabel.Location = new System.Drawing.Point(719, 152);
            this.flightTimeEngineerLabel.Name = "flightTimeEngineerLabel";
            this.flightTimeEngineerLabel.Size = new System.Drawing.Size(150, 29);
            this.flightTimeEngineerLabel.TabIndex = 100;
            this.flightTimeEngineerLabel.Text = "Route Time";
            this.flightTimeEngineerLabel.UseMnemonic = false;
            // 
            // loadEngineerLogOutButton
            // 
            this.loadEngineerLogOutButton.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.loadEngineerLogOutButton.BackColor = System.Drawing.Color.Red;
            this.loadEngineerLogOutButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(29)))), ((int)(((byte)(50)))));
            this.loadEngineerLogOutButton.FlatAppearance.BorderSize = 0;
            this.loadEngineerLogOutButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.loadEngineerLogOutButton.Font = new System.Drawing.Font("Bahnschrift", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.loadEngineerLogOutButton.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.loadEngineerLogOutButton.Location = new System.Drawing.Point(12, 12);
            this.loadEngineerLogOutButton.Name = "loadEngineerLogOutButton";
            this.loadEngineerLogOutButton.Size = new System.Drawing.Size(105, 40);
            this.loadEngineerLogOutButton.TabIndex = 104;
            this.loadEngineerLogOutButton.TabStop = false;
            this.loadEngineerLogOutButton.Text = "Logout";
            this.loadEngineerLogOutButton.UseVisualStyleBackColor = false;
            this.loadEngineerLogOutButton.Click += new System.EventHandler(this.loadEngineerLogOutButton_Click);
            // 
            // LoadEngineerForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(22)))), ((int)(((byte)(31)))));
            this.ClientSize = new System.Drawing.Size(1216, 712);
            this.Controls.Add(this.flightTimeEngineerLabel);
            this.Controls.Add(this.destinationEngineerLabel);
            this.Controls.Add(this.originEngineerLabel);
            this.Controls.Add(this.dateEngineerLabel);
            this.Controls.Add(this.flowLayoutPanel1);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(1232, 751);
            this.Name = "LoadEngineerForm";
            this.Text = "LoadEngineerForm";
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button loadEngineerExitButton;
        private System.Windows.Forms.Panel panel3;
        public System.Windows.Forms.Button browseFlightsMarketingButton;
        public System.Windows.Forms.Button addNewFlightButton;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.Label destinationEngineerLabel;
        private System.Windows.Forms.Label originEngineerLabel;
        private System.Windows.Forms.Label dateEngineerLabel;
        private System.Windows.Forms.Label flightTimeEngineerLabel;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.ComboBox destinationComboBox;
        private System.Windows.Forms.ComboBox originComboBox;
        public System.Windows.Forms.Button loadEngineerLogOutButton;
    }
}