// <auto-generated />
using System;
using Air3550.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Air3550.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20210429001936_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Air3550.Database.Models.Aircraft", b =>
                {
                    b.Property<int>("AircraftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftMaxFlyingDistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AircraftID");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            AircraftID = 1,
                            AircraftCapacity = 160,
                            AircraftMaxFlyingDistance = 2835,
                            AircraftName = "Boeing 737-800(738)"
                        },
                        new
                        {
                            AircraftID = 2,
                            AircraftCapacity = 246,
                            AircraftMaxFlyingDistance = 6020,
                            AircraftName = "Boeing 767-400 ER"
                        },
                        new
                        {
                            AircraftID = 3,
                            AircraftCapacity = 539,
                            AircraftMaxFlyingDistance = 6089,
                            AircraftName = "Boeing 747"
                        });
                });

            modelBuilder.Entity("Air3550.Database.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CityLatitude")
                        .HasColumnType("Decimal(8,6)");

                    b.Property<decimal>("CityLongitude")
                        .HasColumnType("Decimal(9,6)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityNameCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            CityLatitude = 33.636667m,
                            CityLongitude = -84.428056m,
                            CityName = "Atlanta",
                            CityNameCode = "ATL"
                        },
                        new
                        {
                            CityID = 2,
                            CityLatitude = 36.126667m,
                            CityLongitude = -86.681944m,
                            CityName = "Nashville",
                            CityNameCode = "BNA"
                        },
                        new
                        {
                            CityID = 3,
                            CityLatitude = 41.411667m,
                            CityLongitude = -81.849722m,
                            CityName = "Cleveland",
                            CityNameCode = "CLE"
                        },
                        new
                        {
                            CityID = 4,
                            CityLatitude = 39.861667m,
                            CityLongitude = -104.673056m,
                            CityName = "Denver",
                            CityNameCode = "DEN"
                        },
                        new
                        {
                            CityID = 5,
                            CityLatitude = 32.896944m,
                            CityLongitude = -97.038056m,
                            CityName = "Dallas",
                            CityNameCode = "DFW"
                        },
                        new
                        {
                            CityID = 6,
                            CityLatitude = 42.2125m,
                            CityLongitude = -83.353333m,
                            CityName = "Detroit",
                            CityNameCode = "DTW"
                        },
                        new
                        {
                            CityID = 7,
                            CityLatitude = 26.0725m,
                            CityLongitude = -80.152778m,
                            CityName = "Fort Lauderdale",
                            CityNameCode = "FLL"
                        },
                        new
                        {
                            CityID = 8,
                            CityLatitude = 40.775m,
                            CityLongitude = -73.875m,
                            CityName = "Queens",
                            CityNameCode = "LGA"
                        },
                        new
                        {
                            CityID = 9,
                            CityLatitude = 33.9425m,
                            CityLongitude = -118.408056m,
                            CityName = "Los Angeles",
                            CityNameCode = "LAX"
                        },
                        new
                        {
                            CityID = 10,
                            CityLatitude = 41.978611m,
                            CityLongitude = -87.904722m,
                            CityName = "Chicago",
                            CityNameCode = "ORD"
                        },
                        new
                        {
                            CityID = 11,
                            CityLatitude = 47.448889m,
                            CityLongitude = -122.309444m,
                            CityName = "Seattle",
                            CityNameCode = "SEA"
                        });
                });

            modelBuilder.Entity("Air3550.Database.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerAccountLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerCreditCardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            CurrentPoints = 0,
                            CustomerAccountLevel = 1,
                            CustomerAddress = "",
                            CustomerAge = 0,
                            CustomerCreditCardNumber = "",
                            CustomerFirstName = "",
                            CustomerLastName = "",
                            CustomerPassword = "CkUr/9qzo+RG6KmxbOG4pmhSdZj28kLqQWfMVVCev214e/xDfHkHECGnqdLoeruRdT01jlPqAsAQoa79RyFg2iocTW//",
                            CustomerPhoneNumber = "",
                            CustomerUsername = "accountant",
                            UsedPoints = 0
                        },
                        new
                        {
                            CustomerID = 2,
                            CurrentPoints = 0,
                            CustomerAccountLevel = 2,
                            CustomerAddress = "",
                            CustomerAge = 0,
                            CustomerCreditCardNumber = "",
                            CustomerFirstName = "",
                            CustomerLastName = "",
                            CustomerPassword = "kPENY3iPYXZ8NHy73Xb9dvsqr6ulVn+aOWiBO8HPGvde5FZj/RmrV6sHXG6D+7yH1bpGLK+Zf4pKTqSlDyoPE6pJwiAUeDNsRw==",
                            CustomerPhoneNumber = "",
                            CustomerUsername = "loadengineer",
                            UsedPoints = 0
                        },
                        new
                        {
                            CustomerID = 3,
                            CurrentPoints = 0,
                            CustomerAccountLevel = 4,
                            CustomerAddress = "",
                            CustomerAge = 0,
                            CustomerCreditCardNumber = "",
                            CustomerFirstName = "",
                            CustomerLastName = "",
                            CustomerPassword = "PQ86GB9720AOnAvx/EptQ1umzC6InrghCtTmc2iwXP/iIpYuASVBrWvr/o8h1SfZXtpZUmk2orsmhlZCqat6btMkH8b2Hnb4/e4u",
                            CustomerPhoneNumber = "",
                            CustomerUsername = "flightmanager",
                            UsedPoints = 0
                        },
                        new
                        {
                            CustomerID = 4,
                            CurrentPoints = 0,
                            CustomerAccountLevel = 3,
                            CustomerAddress = "",
                            CustomerAge = 0,
                            CustomerCreditCardNumber = "",
                            CustomerFirstName = "",
                            CustomerLastName = "",
                            CustomerPassword = "/ye1E/NpN0Y5FABSBdZDn2BxINlXBoeRj7vHCybDM46Gm9RHrjC2KpawIs8/ABDw1njYj1NAPf9mkczoJYchsDdTxmpPh6/WWwOb/g==",
                            CustomerPhoneNumber = "",
                            CustomerUsername = "marketingmanager",
                            UsedPoints = 0
                        });
                });

            modelBuilder.Entity("Air3550.Database.Models.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightRouteID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightID");

                    b.HasIndex("FlightRouteID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Air3550.Database.Models.Route", b =>
                {
                    b.Property<int>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightAircraftAircraftID")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("FlightDepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteDestinationCityID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteOriginCityID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("INTEGER");

                    b.HasKey("RouteID");

                    b.HasIndex("FlightAircraftAircraftID");

                    b.HasIndex("RouteDestinationCityID");

                    b.HasIndex("RouteOriginCityID");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteID = 1,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 6, 20, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 2,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 10, 20, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 3,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 14, 20, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 4,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 18, 20, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 5,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 8, 20, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 6,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 12, 20, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 7,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 16, 20, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 8,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 20, 20, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 9,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 6, 40, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 10,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 10, 40, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 11,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 14, 40, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 12,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 18, 40, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 13,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 8, 40, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 14,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 12, 40, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 15,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 16, 40, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 16,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 20, 40, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 17,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 7, 0, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 18,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 11, 0, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 19,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 15, 0, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 20,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 19, 0, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 21,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 22,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 13, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 23,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 17, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 24,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 21, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 25,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 5, 0, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 26,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 27,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 13, 0, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 28,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 17, 0, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 3,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 29,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 7, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 30,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 11, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 31,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 15, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 32,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 19, 0, 0, 0),
                            RouteDestinationCityID = 3,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 33,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 4, 20, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 34,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 8, 20, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 35,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 12, 20, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 36,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 16, 20, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 37,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 2, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 38,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 6, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 39,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 10, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 40,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 14, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 41,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 0, 20, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 42,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 4, 20, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 43,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 8, 20, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 44,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 12, 20, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 8,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 45,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 11, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 46,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 15, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 47,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 19, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 48,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 23, 20, 0, 0),
                            RouteDestinationCityID = 8,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 49,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 8, 15, 0, 0),
                            RouteDestinationCityID = 7,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 50,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 12, 15, 0, 0),
                            RouteDestinationCityID = 7,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 51,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 16, 15, 0, 0),
                            RouteDestinationCityID = 7,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 52,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 20, 15, 0, 0),
                            RouteDestinationCityID = 7,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 53,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 10, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 7,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 54,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 14, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 7,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 55,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 18, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 7,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 56,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 22, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 7,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 57,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 4, 15, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 58,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 8, 15, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 59,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 12, 15, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 60,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 16, 15, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 61,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 6, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 62,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 10, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 63,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 14, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 64,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 18, 15, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 65,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 4, 30, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 66,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 8, 30, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 67,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 12, 30, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 68,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 16, 30, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 69,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 70,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 13, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 71,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 17, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 72,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 21, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 73,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 5, 30, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 74,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 75,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 13, 30, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 76,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 17, 30, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 1,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 77,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 10, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 78,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 14, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 79,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 18, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 80,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 22, 30, 0, 0),
                            RouteDestinationCityID = 1,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 81,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 11, 45, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 82,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 15, 45, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 83,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 19, 45, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 84,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 23, 45, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 85,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 8, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 86,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 12, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 87,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 16, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 88,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 20, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 89,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 2, 45, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 90,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 6, 45, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 91,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 10, 45, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 92,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 14, 45, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 93,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 3, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 94,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 7, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 95,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 11, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 96,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 15, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 97,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 0, 45, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 98,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 4, 45, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 99,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 8, 45, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 100,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 12, 45, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 101,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 1, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 102,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 5, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 103,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 9, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 104,
                            FlightAircraftAircraftID = 2,
                            FlightDepartureTime = new TimeSpan(0, 13, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 105,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 4, 45, 0, 0),
                            RouteDestinationCityID = 11,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 106,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 8, 45, 0, 0),
                            RouteDestinationCityID = 11,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 107,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 12, 45, 0, 0),
                            RouteDestinationCityID = 11,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 108,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 16, 45, 0, 0),
                            RouteDestinationCityID = 11,
                            RouteOriginCityID = 4,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 109,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 5, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 11,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 110,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 9, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 11,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 111,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 13, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 11,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 112,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 17, 45, 0, 0),
                            RouteDestinationCityID = 4,
                            RouteOriginCityID = 11,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 113,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 10, 50, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 114,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 14, 50, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 115,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 18, 50, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 116,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 22, 50, 0, 0),
                            RouteDestinationCityID = 5,
                            RouteOriginCityID = 9,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 117,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 11, 50, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 118,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 15, 50, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 119,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 19, 50, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 120,
                            FlightAircraftAircraftID = 3,
                            FlightDepartureTime = new TimeSpan(0, 23, 50, 0, 0),
                            RouteDestinationCityID = 9,
                            RouteOriginCityID = 5,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 121,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 8, 50, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 122,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 12, 50, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 123,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 16, 50, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 124,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 20, 50, 0, 0),
                            RouteDestinationCityID = 6,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 125,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 9, 50, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 126,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 13, 50, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 127,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 17, 50, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 128,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 21, 50, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 6,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 129,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 8, 55, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 130,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 12, 55, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 131,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 16, 55, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 132,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 20, 55, 0, 0),
                            RouteDestinationCityID = 2,
                            RouteOriginCityID = 10,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 133,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 9, 55, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 134,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 13, 55, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 135,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 17, 55, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        },
                        new
                        {
                            RouteID = 136,
                            FlightAircraftAircraftID = 1,
                            FlightDepartureTime = new TimeSpan(0, 21, 55, 0, 0),
                            RouteDestinationCityID = 10,
                            RouteOriginCityID = 2,
                            isCanceled = false
                        });
                });

            modelBuilder.Entity("Air3550.Database.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId");

                    b.HasIndex("FlightID");

                    b.HasIndex("TransactionID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Air3550.Database.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PointsClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionBillingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionBookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionCustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TransactionTotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionID");

                    b.HasIndex("TransactionCustomerID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Air3550.Database.Models.Flight", b =>
                {
                    b.HasOne("Air3550.Database.Models.Route", "FlightRoute")
                        .WithMany()
                        .HasForeignKey("FlightRouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightRoute");
                });

            modelBuilder.Entity("Air3550.Database.Models.Route", b =>
                {
                    b.HasOne("Air3550.Database.Models.Aircraft", "FlightAircraft")
                        .WithMany()
                        .HasForeignKey("FlightAircraftAircraftID");

                    b.HasOne("Air3550.Database.Models.City", "RouteDestinationCity")
                        .WithMany()
                        .HasForeignKey("RouteDestinationCityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Air3550.Database.Models.City", "RouteOriginCity")
                        .WithMany()
                        .HasForeignKey("RouteOriginCityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightAircraft");

                    b.Navigation("RouteDestinationCity");

                    b.Navigation("RouteOriginCity");
                });

            modelBuilder.Entity("Air3550.Database.Models.Ticket", b =>
                {
                    b.HasOne("Air3550.Database.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Air3550.Database.Models.Transaction", "Transaction")
                        .WithMany("Tickets")
                        .HasForeignKey("TransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Air3550.Database.Models.Transaction", b =>
                {
                    b.HasOne("Air3550.Database.Models.Customer", "TransactionCustomer")
                        .WithMany()
                        .HasForeignKey("TransactionCustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionCustomer");
                });

            modelBuilder.Entity("Air3550.Database.Models.Flight", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Air3550.Database.Models.Transaction", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
